config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :products do 
    resources :messages, only:[:new, :create, :show]
  end
  resources :subcategories
  resources :categories
  devise_for :users
  get 'my_product', to: 'products#my_product', as: 'my_product'
  root to: 'home#page'
end

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-md navbar-dark sticky-top bg-dark">
<a class="navbar-brand" href="#">Hand-Me-Downs</a>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <% if user_signed_in? %>
            <ul class="navbar-nav mr-auto">   
                <li class="nav-item">
                    <%= link_to "Home", products_path, class: "nav-link active" %>
                </li>
                <li class="nav-item">
                    <%= link_to "Categories", categories_path, class: "nav-link active" %>
                </li>
                <li class="nav-item">
                    <%= link_to "New Post", new_product_path, class: "nav-link active" %>
                </li>
                <li class="nav-item">
                    <%= link_to "My Posts", my_product_path, class: "nav-link active" %>
                </li>
                <li class="nav-item">
                    <%= link_to "Messages", messages_path, class: "nav-link active" %>
                </li>
                <li class="nav-item">
                    <%= link_to "Sign Out", destroy_user_session_path, method: "delete", class: "nav-link active" %>
                </li>
        <% else %>
                 <li class="nav-item">
                    <%= link_to "Home", root_path, class: "nav-link active" %>
                </li>
                <li class="nav-item">
                    <%= link_to "Sign In", new_user_session_path, class: "nav-link active" %>
                </li>
                <li class="nav-item">
                    <%= link_to "Sign Up", new_user_registration_path, class: "nav-link active" %> 
                </li>
            </ul>
        <% end %>
    <div>
</nav> 