config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :products do 
    resources :messages, only:[:new, :create, :show]
  end
  resources :subcategories
  resources :categories
  devise_for :users
  get 'my_product', to: 'products#my_product', as: 'my_product'
  root to: 'home#page'
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  belongs_to :subcategory
  has_one_attached :image
  has_many :receiver_messages
  has_many :messages
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]
  # Restricting accsess for non logged in users with user only before action
  before_action :authenticate_user!, only: [:new, :create, :update, :edit, :destroy, :index, :show]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  def my_product
    @users = User.all
    @products = Product.all
  end 

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.create(title: product_params[:title], description: product_params[:description], used: product_params[:used], price: product_params[:price], subcategory_id: product_params[:subcategory_id], image: product_params[:image], user: current_user)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title, :description, :used, :price, :subcategory_id, :image)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="card mb-3 mx-auto" style="max-width: 540px;">
    <div class="card-body">
      <div class="field mb-3">
        <%= form.label :subcategory_id, { class: "form-label"} %>
        <%= form.select :subcategory_id, Subcategory.all.collect {|s| [ s.name, s.id ] } %>
      </div>

      <div class="field mb-3">
        <%= form.label :title, { class: "form-label"} %>
        <%= form.text_field :title, { class: "form-control"} %>
      </div>

      <div class="field mb-3">
        <%= form.label :description, { class: "form-label"} %>
        <%= form.text_area :description, { class: "form-control", rows: "5" } %>
      </div>

      <div class="field mb-3">
        <%= form.label :price, { class: "form-label"} %>
        <%= form.text_field :price, { class: "form-control", rows: "5"} %>
      </div>

      <div class="field mb-3">
        <%= form.label :image, { class: "form-label"} %>
        <%= form.file_field :image, accept: "image/jpg, image/png, image/jpeg" %>
      </div>

      <div class="field mb-3">
        <%= form.label :used, { class: "form-label"} %>
        <%= form.check_box :used %>
      </div>

      <div class="actions">
        <%= form.submit %>
      </div>
    </div>
  </div>
<% end %>

<br>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Products Feed</h1>

<br>
<br>

<% @products.reverse_each do |product| %>
  <div class="card mb-3 mx-auto" style="max-width: 540px;">
    <div class="row no-gutters">
      <div class="col-md-4">
        <%= image_tag product.image, class: "card-img" if product.image.attached? %>
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title"><%= link_to product.title, product_path(product) %></h5>
          <p class="card-text"><%= product.description %></p>
          <p class="card-text"><small class="text-muted"><%= time_ago_in_words product.created_at %></small></p>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/products/my_product.html.erb
<h1>My Products</h1>

<% current_user.products.reverse_each do |product| %>
  <div class="card mb-3 mx-auto" style="max-width: 540px;">
    <div class="row no-gutters">
      <div class="col-md-4">
        <%= image_tag product.image, class: "card-img" if product.image.attached? %>
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title"><%= link_to product.title, product_path(product) %></h5>
          <p class="card-text"><%= product.description %></p>
          <p class="card-text"><small class="text-muted"><%= time_ago_in_words product.created_at %></small></p>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<div class="card col-9 mx-auto">
  <div class="card-header">
    Posted By <%= @product.user.username %>
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= @product.title %></h5>
    <div class="mx-auto">
        <%= image_tag @product.image, class: "card-img" if @product.image.attached? %>
    </div>
    <p class="card-text"><strong>Description: </strong><%= @product.description %></p>
    <p class="card-text"><strong>Used: </strong><%= @product.used %></p>
    <p class="card-text"><strong>Price: </strong>$ <%= @product.price %></p>
    <%= link_to "Send Message", new_message_path(receiver_id: @product.user, sender_id: current_user, product_id: @product), class: "btn btn-primary" %>
  </div>
</div>